### ISSUE TITLE
[QUESTION] database/schema updates

### ISSUE THREAD

**Issue by imduffy15** [techdev-solutions/trackr-backend#17]
Its likely I'm missing something.... However, I'm curious to know what made you go for the demonstrated way of handling database schema creation and updates over solutions like liquibase[1] or flyway[2]? 

[1] http://www.liquibase.org/
[2] http://flywaydb.org/

**Comment by FrontierPsychiatrist** [comment]
We are actually using flyway, the folder https://github.com/techdev-solutions/trackr-backend/tree/master/src/main/database contains scripts that are compatible with it.

After our next release (currently in the development branch) we will use the embedded flyway feature of Spring Boot.
