### ISSUE TITLE
more than trackr backend one servers?

### ISSUE THREAD

**Issue by svennela** [techdev-solutions/trackr-backend#20]
Hi ,

Is it possible to deploy trackr backend two different servers? if yes, how do i share or access user information?

Sridhar

**Comment by FrontierPsychiatrist** [comment]
As of our migration to Spring Boot we use the backend as a stateless OAuth2 resource server.

The user information is contained in the token used to access the resource server and maintained by the authorization server (which we haven't open sourced yet, basically it's just a Spring Security OAuth2 Authorization Server).

When using this approach you can easily deploy the backend to two different servers. If you don't want to use OAuth (like in the http-basic profile) you need some shared session, e.g. with Spring Session.

Regardless of what you choose, you can request the principal from the `/principal` endpoint in the trackr backend. See [here](http://techdev-solutions.github.io/trackr-api-documentation/api/principal.html), although the documentation page is a bit outdated.

**Comment by svennela** [comment]
Thank you for response. just to my understanding, frontend will talk to auth server and get token with the token, you access resource server right? current frontend repo is doing it? do you have code snippet?

**Comment by FrontierPsychiatrist** [comment]
Yes, that is correct.

This template displays a link to the auth server
https://github.com/techdev-solutions/trackr-frontend/blob/development/src/modules/base/partials/authorization.tpl.html

This controller parses the response and sets it into the $http.defaults of AngularJS.
https://github.com/techdev-solutions/trackr-frontend/blob/development/src/modules/base/controllers/authorizationController.js

**Comment by svennela** [comment]
Hi ,
Thank you. Any plans on making open sourcing authorization server?

**Comment by FrontierPsychiatrist** [comment]
Yeah, we just have to doublecheck there's nothing confidential in the repo - then we will make it public.

**Comment by alexhanschke** [comment]
hi @svennela - thanks for your feedback. we just double-checked the code and there is good news: the portal is now open-source as well. you can find it here: https://github.com/techdev-solutions/techdev-portal

cheers,
alex
